// test-apps/vue/src/components/LanguageSwitcher.vue
<script setup lang="ts">
import { useI18n } from "@comvi/vue";

const { locale, setLocale, isLoading } = useI18n();
const locales = ["en", "de", "fr", "es", "uk", "ar"];

const onLocaleChange = async (event: Event) => {
  const target = event.target as HTMLSelectElement;
  await setLocale(target.value);
};
</script>

<template>
  <select
    :value="locale"
    :disabled="isLoading"
    class="border border-gray-300 rounded px-2 py-1 bg-white text-gray-700 disabled:opacity-50"
    @change="onLocaleChange"
  >
    <option v-for="loc in locales" :key="loc" :value="loc">
      {{ loc.toUpperCase() }}
    </option>
  </select>
</template>

// test-apps/svelte/src/lib/components/LanguageSwitcher.svelte
<script lang="ts">
  import { useI18n } from '@comvi/svelte';

  const { locale, setLocale } = useI18n();

  const locales = ['en', 'de', 'fr', 'es', 'uk', 'ar'];

  function handleChange(event: Event) {
    const target = event.target as HTMLSelectElement;
    setLocale(target.value);
  }
</script>

<select
  value={$locale}
  on:change={handleChange}
  class="border border-gray-300 rounded px-2 py-1 bg-white text-gray-700"
>
  {#each locales as loc (loc)}
    <option value={loc}>{loc.toUpperCase()}</option>
  {/each}
</select>
