// packages/solid/src/useI18n.ts
import { type Accessor } from "solid-js";
import {
  formatCurrency,
  formatDate,
  formatNumber,
  formatRelativeTime,
  getTextDirection,
} from "@comvi/core";
import { useI18nContextValue } from "./context";
import type {
  I18n,
  TranslationParams,
  TranslationResult,
  VirtualNode,
  FlattenedTranslations,
  DefaultTranslationParams,
  DefaultParamsSnapshot,
} from "@comvi/core";

function isVirtualNode(value: unknown): value is VirtualNode {
  return (
    value !== null &&
    typeof value === "object" &&
    "type" in value &&
    (value.type === "text" || value.type === "element" || value.type === "fragment")
  );
}

function virtualNodeToText(node: VirtualNode): string {
  if (node.type === "text") {
    return node.text;
  }

  let text = "";
  for (const child of node.children) {
    if (typeof child === "string") {
      text += child;
      continue;
    }
    text += virtualNodeToText(child);
  }

  return text;
}

function translationResultToString(result: TranslationResult): string {
  if (typeof result === "string") {
    return result;
  }

  let text = "";
  for (const part of result) {
    if (typeof part === "string") {
      text += part;
      continue;
    }

    if (isVirtualNode(part)) {
      text += virtualNodeToText(part);
      continue;
    }

    text += String(part);
  }

  return text;
}

type BoundDefaultNamespaceParams<
  NS extends string,
  K extends string,
  D extends DefaultTranslationParams,
> = `${NS}:${K}` extends keyof import("@comvi/core").TranslationKeys
  ? import("@comvi/core").ParamsArg<`${NS}:${K}` & keyof import("@comvi/core").TranslationKeys, D>
  : [params?: TranslationParams];

type UseI18nTranslation<
  DefaultNS extends string | undefined,
  D extends DefaultTranslationParams,
> = {
  /**
   * Translation function - namespaced keys (explicit ns in params)
   */
  <NS extends import("@comvi/core").Namespaces, K extends import("@comvi/core").NamespacedKeys<NS>>(
    key: K,
    ...params: import("@comvi/core").NamespacedParamsArg<NS, K, D>
  ): string;

  /**
   * Translation function - typed keys
   */
  <K extends import("@comvi/core").DefaultNsKeys>(
    key: K,
    ...params: import("@comvi/core").ParamsArg<K, D>
  ): string;

  /** Permissive overload - only active when TranslationKeys is empty */
  (key: import("@comvi/core").PermissiveKey, params?: TranslationParams): string;
} & (DefaultNS extends import("@comvi/core").Namespaces
  ? {
      /**
       * Namespace-bound shorthand when useI18n(ns) is provided.
       * Allows `t('title')` instead of `t('title', { ns: 'admin' })`.
       */
      <K extends import("@comvi/core").NamespacedKeys<DefaultNS>>(
        key: K,
        ...params: BoundDefaultNamespaceParams<DefaultNS, K, D>
      ): string;
    }
  : {});

type UseI18nRawTranslation<
  DefaultNS extends string | undefined,
  D extends DefaultTranslationParams,
> = {
  /**
   * Raw translation function - namespaced keys (explicit ns in params)
   */
  <NS extends import("@comvi/core").Namespaces, K extends import("@comvi/core").NamespacedKeys<NS>>(
    key: K,
    ...params: import("@comvi/core").NamespacedParamsArg<NS, K, D>
  ): TranslationResult;

  /**
   * Raw translation function - typed keys
   */
  <K extends import("@comvi/core").DefaultNsKeys>(
    key: K,
    ...params: import("@comvi/core").ParamsArg<K, D>
  ): TranslationResult;

  /** Permissive overload - only active when TranslationKeys is empty */
  (key: import("@comvi/core").PermissiveKey, params?: TranslationParams): TranslationResult;
} & (DefaultNS extends import("@comvi/core").Namespaces
  ? {
      /**
       * Namespace-bound shorthand when useI18n(ns) is provided.
       * Allows `tRaw('title')` instead of `tRaw('title', { ns: 'admin' })`.
       */
      <K extends import("@comvi/core").NamespacedKeys<DefaultNS>>(
        key: K,
        ...params: BoundDefaultNamespaceParams<DefaultNS, K, D>
      ): TranslationResult;
    }
  : {});

export interface UseI18nReturn<
  DefaultNS extends string | undefined = undefined,
  D extends DefaultTranslationParams = {},
> {
  /**
   * Reactive translation function
   * Automatically re-renders when language or translations change
   * Always returns plain text.
   *
   * @example
   * ```tsx
   * const { t } = useI18n();
   *
   * // Use directly in JSX - no double call needed!
   * <p>{t('greeting')}</p>
   * <p>{t('welcome', { name: 'Alice' })}</p>
   * ```
   */
  t: UseI18nTranslation<DefaultNS, D>;

  /**
   * Raw translation function returning full core TranslationResult.
   * Use for advanced scenarios that need structured output.
   */
  tRaw: UseI18nRawTranslation<DefaultNS, D>;

  /** Current locale as a reactive accessor */
  locale: Accessor<string>;

  /** Loading state as a reactive accessor */
  isLoading: Accessor<boolean>;

  /** Initializing state as a reactive accessor */
  isInitializing: Accessor<boolean>;

  /** Initialized state as a reactive accessor */
  isInitialized: Accessor<boolean>;

  /** Translation cache revision (for triggering reactivity) */
  cacheRevision: Accessor<number>;

  /** Reactive shallow snapshot of instance-level interpolation defaults. */
  defaultParams: Accessor<DefaultParamsSnapshot<D>>;

  // ===== Critical Methods =====

  /** Change the current locale and wait for translations to load */
  setLocale: I18n["setLocaleAsync"];

  /** Add translations programmatically at runtime */
  addTranslations: I18n["addTranslations"];

  /** Load a new namespace dynamically */
  addActiveNamespace: I18n["addActiveNamespace"];

  // ===== Advanced Methods =====

  /** Configure fallback locale chain */
  setFallbackLocale: I18n["setFallbackLocale"];

  /** Replace instance-level interpolation defaults. */
  setDefaultParams: I18n<D>["setDefaultParams"];

  /** Register callback for missing keys */
  onMissingKey: I18n["onMissingKey"];

  /** Register callback for load errors */
  onLoadError: I18n["onLoadError"];

  /** Clear translations from cache */
  clearTranslations: I18n["clearTranslations"];

  /** Force reload translations from loader */
  reloadTranslations: I18n["reloadTranslations"];

  // ===== Informational Methods =====

  /** Check if a locale is loaded for a namespace */
  hasLocale: I18n["hasLocale"];

  /** Check if a translation exists */
  hasTranslation: I18n["hasTranslation"];

  /** Get list of all loaded locales */
  getLoadedLocales: () => string[];

  /** Get list of active namespaces */
  getActiveNamespaces: I18n["getActiveNamespaces"];

  /** Get default namespace */
  getDefaultNamespace: I18n["getDefaultNamespace"];

  /** Get direct access to translation cache */
  getTranslationCache: () => ReadonlyMap<string, FlattenedTranslations>;

  // ===== Event Subscription =====

  /**
   * Subscribe to i18n events
   * Provides direct access to core event system for advanced use cases
   */
  on: I18n["on"];

  /** Report an error to the configured onError handler */
  reportError: I18n["reportError"];

  // ===== Formatting =====

  /** Format a number using the current locale */
  formatNumber: (value: number, options?: Intl.NumberFormatOptions, locale?: string) => string;

  /** Format a date using the current locale */
  formatDate: (
    value: Date | number,
    options?: Intl.DateTimeFormatOptions,
    locale?: string,
  ) => string;

  /** Format a number as currency using the current locale */
  formatCurrency: (
    value: number,
    currency: string,
    options?: Intl.NumberFormatOptions,
    locale?: string,
  ) => string;

  /** Format a relative time ("2 hours ago", "in 3 days") using the current locale */
  formatRelativeTime: (
    value: number,
    unit: Intl.RelativeTimeFormatUnit,
    options?: Intl.RelativeTimeFormatOptions,
    locale?: string,
  ) => string;

  /** Text direction for the current locale as a reactive accessor */
  dir: () => "ltr" | "rtl";
}

/**
 * Hook to access i18n functionality in SolidJS components
 * Must be used within a component wrapped by I18nProvider
 *
 * @param ns - Optional namespace to scope translations to
 * @returns Object with reactive translation function and i18n methods
 *
 * @example Basic usage
 * ```tsx
 * import { useI18n } from '@comvi/solid';
 *
 * function Greeting() {
 *   const { t, locale, setLocale } = useI18n();
 *
 *   return (
 *     <div>
 *       <p>{t('greeting')}</p>
 *       <p>Current locale: {locale()}</p>
 *       <button onClick={() => setLocale('fr')}>Switch to French</button>
 *     </div>
 *   );
 * }
 * ```
 *
 * @example With parameters
 * ```tsx
 * import { useI18n } from '@comvi/solid';
 * import { createSignal } from 'solid-js';
 *
 * function Counter() {
 *   const { t } = useI18n();
 *   const [count, setCount] = createSignal(5);
 *
 *   return <p>{t('items', { count: count() })}</p>;
 * }
 * ```
 *
 * @example Dynamic namespace loading
 * ```tsx
 * import { useI18n } from '@comvi/solid';
 * import { createSignal } from 'solid-js';
 *
 * function AdminPanel() {
 *   const { t, addActiveNamespace, isLoading } = useI18n();
 *   const [isAdminLoaded, setIsAdminLoaded] = createSignal(false);
 *
 *   async function loadAdmin() {
 *     await addActiveNamespace('admin');
 *     setIsAdminLoaded(true);
 *   }
 *
 *   return (
 *     <Show when={!isLoading()} fallback={<p>Loading...</p>}>
 *       <Show when={isAdminLoaded()} fallback={<button onClick={loadAdmin}>Load Admin</button>}>
 *         <p>{t('dashboard', { ns: 'admin' })}</p>
 *       </Show>
 *     </Show>
 *   );
 * }
 * ```
 */
export function useI18n<
  DefaultNS extends string | undefined = undefined,
  D extends DefaultTranslationParams = {},
>(ns?: DefaultNS): UseI18nReturn<DefaultNS, D> {
  const ctx = useI18nContextValue();

  /**
   * Reactive raw translation function.
   * When called within a reactive context (JSX, createMemo, createEffect),
   * it automatically tracks language and cache changes.
   */
  const tRaw = ((key: string, params?: TranslationParams): TranslationResult => {
    // Access signals to establish reactive dependencies.
    // This works because SolidJS tracks signal access in reactive contexts.
    // Only subscribe to the global locale when the caller didn't pin one
    // explicitly — tRaw(key, { locale }) does not depend on the active locale,
    // so tracking it would cause needless recomputes on global locale changes.
    if (params?.locale === undefined) {
      ctx.signals.locale();
    }
    ctx.signals.cacheRevision();
    if (ns === undefined) {
      ctx.signals.defaultNamespace();
    }

    // No params: preserve core fast-path and avoid unnecessary object allocation.
    if (params == null) {
      if (ns === undefined) {
        return ctx.i18n.tRaw(key as never);
      }
      return ctx.i18n.tRaw(key as never, { ns } as TranslationParams);
    }

    // User explicitly provided namespace - never override it.
    if (params.ns !== undefined || ns === undefined) {
      return ctx.i18n.tRaw(key as never, params as TranslationParams);
    }

    // Merge default namespace only when needed.
    return ctx.i18n.tRaw(key as never, { ns, ...params } as TranslationParams);
  }) as UseI18nRawTranslation<DefaultNS, D>;

  /**
   * Reactive translation function that always returns plain text.
   * Structured rich-text output should use `tRaw()` or `<T />`.
   */
  const t = ((key: string, params?: TranslationParams): string => {
    return translationResultToString(tRaw(key as never, params as never));
  }) as UseI18nTranslation<DefaultNS, D>;

  return {
    t,
    tRaw,

    // To support destructuring while maintaining hot-swap capability,
    // we return wrapper accessors instead of returning the getters directly.
    // This ensures ctx.signals.* is called at read time, not at destructure time.
    locale: () => ctx.signals.locale(),
    isLoading: () => ctx.signals.isLoading(),
    isInitializing: () => ctx.signals.isInitializing(),
    isInitialized: () => ctx.signals.isInitialized(),
    cacheRevision: () => ctx.signals.cacheRevision(),
    defaultParams: () => {
      ctx.signals.cacheRevision();
      return ctx.i18n.defaultParams as DefaultParamsSnapshot<D>;
    },

    // Bind all methods dynamically so they always use the current i18n instance.
    // Functions are returned directly to support destructuring safely.
    setLocale: (...args) => ctx.i18n.setLocaleAsync(...args),
    addTranslations: (...args) => ctx.i18n.addTranslations(...args),
    addActiveNamespace: (...args) => ctx.i18n.addActiveNamespace(...args),
    setFallbackLocale: (...args) => ctx.i18n.setFallbackLocale(...args),
    setDefaultParams: (params) => ctx.i18n.setDefaultParams(params as never),
    onMissingKey: (...args) => ctx.i18n.onMissingKey(...args),
    onLoadError: (...args) => ctx.i18n.onLoadError(...args),
    clearTranslations: (...args) => ctx.i18n.clearTranslations(...args),
    reloadTranslations: (...args) => ctx.i18n.reloadTranslations(...args),
    hasLocale: (...args) => ctx.i18n.hasLocale(...args),
    hasTranslation: (...args) => ctx.i18n.hasTranslation(...args),
    getLoadedLocales: () => ctx.i18n.getLoadedLocales(),
    getActiveNamespaces: () => ctx.i18n.getActiveNamespaces(),
    getDefaultNamespace: () => ctx.i18n.getDefaultNamespace(),
    getTranslationCache: () => ctx.i18n.translationCache.getInternalMap(),
    on: (...args) => ctx.i18n.on(...args),
    reportError: (...args) => ctx.i18n.reportError(...args),
    formatNumber: (...args) => formatNumber(ctx.i18n, ...args),
    formatDate: (...args) => formatDate(ctx.i18n, ...args),
    formatCurrency: (...args) => formatCurrency(ctx.i18n, ...args),
    formatRelativeTime: (...args) => formatRelativeTime(ctx.i18n, ...args),
    // Derive from the locale signal so the accessor stays reactive
    dir: () => getTextDirection(ctx.signals.locale()),
  };
}

// packages/react/src/useI18n.ts
import { useMemo } from "react";
import { useI18nContext } from "./I18nProvider";
import { createBoundTranslation } from "@comvi/core";
import type {
  TranslationParams,
  TranslationResult,
  VirtualNode,
  FlattenedTranslations,
  TranslationValue,
  I18nEvent,
  I18nEventData,
  I18n,
} from "@comvi/core";

import { isVirtualNode } from "./utils";

type ReactElementLike = {
  $$typeof: unknown;
  props?: {
    children?: unknown;
  };
};

function isReactElementLike(value: unknown): value is ReactElementLike {
  return (
    value !== null &&
    typeof value === "object" &&
    "$$typeof" in value &&
    "props" in value &&
    typeof (value as { props?: unknown }).props === "object"
  );
}

function virtualNodeToText(node: VirtualNode): string {
  if (node.type === "text") {
    return node.text;
  }

  let text = "";
  for (const child of node.children) {
    if (typeof child === "string") {
      text += child;
      continue;
    }
    text += virtualNodeToText(child);
  }
  return text;
}

function reactNodeToText(node: unknown): string {
  if (node == null || typeof node === "boolean") {
    return "";
  }
  if (typeof node === "string" || typeof node === "number") {
    return String(node);
  }
  if (Array.isArray(node)) {
    let text = "";
    for (const item of node) {
      text += reactNodeToText(item);
    }
    return text;
  }
  if (isVirtualNode(node)) {
    return virtualNodeToText(node);
  }
  if (isReactElementLike(node)) {
    return reactNodeToText(node.props?.children);
  }
  return String(node);
}

function translationResultToString(result: TranslationResult): string {
  if (typeof result === "string") {
    return result;
  }

  let text = "";
  for (const part of result as Array<unknown>) {
    if (typeof part === "string") {
      text += part;
      continue;
    }
    if (isVirtualNode(part)) {
      text += virtualNodeToText(part);
      continue;
    }
    if (isReactElementLike(part)) {
      text += reactNodeToText(part.props?.children);
      continue;
    }
    text += String(part);
  }
  return text;
}

/** Methods bound directly from i18n instance */
const BIND_METHODS = [
  "addTranslations",
  "addActiveNamespace",
  "setFallbackLocale",
  "onLoadError",
  "clearTranslations",
  "reloadTranslations",
  "hasLocale",
  "hasTranslation",
  "getLoadedLocales",
  "getActiveNamespaces",
  "getDefaultNamespace",
  "on",
  "reportError",
  "formatNumber",
  "formatDate",
  "formatCurrency",
  "formatRelativeTime",
] as const;

export interface UseI18nReturn {
  /**
   * Translation function - namespaced keys (when ns is provided)
   *
   * Always returns plain text. If core returns structured output
   * (e.g. VirtualNode arrays), it's flattened to string.
   */
  t<
    NS extends import("@comvi/core").Namespaces,
    K extends import("@comvi/core").NamespacedKeys<NS>,
  >(
    key: K,
    ...params: import("@comvi/core").NamespacedParamsArg<NS, K>
  ): string;

  /**
   * Translation function - typed keys
   *
   * Always returns plain text.
   * For rich-text/tag interpolation rendering, use `tRaw()` or the `<T>` component instead.
   */
  t<K extends import("@comvi/core").DefaultNsKeys>(
    key: K,
    ...params: import("@comvi/core").ParamsArg<K>
  ): string;

  /** Permissive overload - only active when TranslationKeys is empty */
  t(key: import("@comvi/core").PermissiveKey, params?: TranslationParams): string;

  /**
   * Raw translation function returning full core TranslationResult.
   * Use this for advanced scenarios that need structured output.
   */
  tRaw<
    NS extends import("@comvi/core").Namespaces,
    K extends import("@comvi/core").NamespacedKeys<NS>,
  >(
    key: K,
    ...params: import("@comvi/core").NamespacedParamsArg<NS, K>
  ): TranslationResult;
  tRaw<K extends import("@comvi/core").DefaultNsKeys>(
    key: K,
    ...params: import("@comvi/core").ParamsArg<K>
  ): TranslationResult;
  tRaw(key: import("@comvi/core").PermissiveKey, params?: TranslationParams): TranslationResult;

  /** Current locale */
  locale: string;

  /** Translation cache */
  translationCache: ReadonlyMap<string, FlattenedTranslations>;

  /** Loading state */
  isLoading: boolean;

  /** Initializing state */
  isInitializing: boolean;

  // ===== Critical Methods =====

  /** Change the current locale and wait for translations to load */
  setLocale: (locale: string) => Promise<void>;

  /** Add translations programmatically at runtime */
  addTranslations: (translations: Record<string, Record<string, TranslationValue>>) => void;

  /** Load a new namespace dynamically */
  addActiveNamespace: (namespace: string) => Promise<void>;

  // ===== Advanced Methods =====

  /** Configure fallback locale chain */
  setFallbackLocale: (locales: string | string[]) => void;

  /** Register callback for missing keys */
  onMissingKey: (
    callback: (key: string, locale: string, namespace: string) => string | void,
  ) => () => void;

  /** Register callback for load errors */
  onLoadError: (callback: (locale: string, namespace: string, error: Error) => void) => () => void;

  /** Clear translations from cache */
  clearTranslations: (locale?: string, namespace?: string) => void;

  /** Force reload translations from loader */
  reloadTranslations: (locale?: string, namespace?: string) => Promise<void>;

  // ===== Informational Methods =====

  /** Check if a locale is loaded for a namespace */
  hasLocale: (locale: string, namespace?: string) => boolean;

  /** Check if a translation exists */
  hasTranslation: (
    key: string,
    locale?: string,
    namespace?: string,
    checkFallbacks?: boolean,
  ) => boolean;

  /** Get list of all loaded locale codes */
  getLoadedLocales: () => string[];

  /** Get list of active namespaces */
  getActiveNamespaces: () => string[];

  /** Get default namespace */
  getDefaultNamespace: () => string;

  // ===== Formatting =====

  /** Format a number using the current locale */
  formatNumber: (value: number, options?: Intl.NumberFormatOptions) => string;

  /** Format a date using the current locale */
  formatDate: (value: Date | number, options?: Intl.DateTimeFormatOptions) => string;

  /** Format a number as currency using the current locale */
  formatCurrency: (value: number, currency: string, options?: Intl.NumberFormatOptions) => string;

  /** Format a relative time ("2 hours ago", "in 3 days") using the current locale */
  formatRelativeTime: (
    value: number,
    unit: Intl.RelativeTimeFormatUnit,
    options?: Intl.RelativeTimeFormatOptions,
  ) => string;

  /** Text direction for the current locale ("ltr" or "rtl") */
  dir: "ltr" | "rtl";

  // ===== Event Subscription =====

  /**
   * Subscribe to i18n events
   * Provides direct access to core event system for advanced use cases
   *
   * @example
   * ```tsx
   * import { useI18n } from '@comvi/react';
   * import { useEffect } from 'react';
   *
   * function MyComponent() {
   *   const { on } = useI18n();
   *
   *   useEffect(() => {
   *     const unsubscribe = on('localeChanged', ({ from, to }) => {
   *       analytics.track('locale_changed', { from, to });
   *     });
   *
   *     return () => unsubscribe();
   *   }, [on]);
   *
   *   return <div>...</div>;
   * }
   * ```
   */
  on: <E extends I18nEvent>(event: E, callback: (payload: I18nEventData[E]) => void) => () => void;

  /** Report an error to the configured onError handler */
  reportError: I18n["reportError"];
}

/**
 * Hook to access i18n functionality in React components
 * Must be used within an I18nProvider
 *
 * @param ns - Optional namespace to scope translations to
 * @returns Object with translation function, reactive state, and i18n methods
 *
 * @example Basic usage
 * ```tsx
 * import { useI18n } from '@comvi/react';
 *
 * function MyComponent() {
 *   const { t, locale } = useI18n();
 *
 *   return (
 *     <div>
 *       <p>{t('greeting')}</p>
 *       <p>Current locale: {locale}</p>
 *     </div>
 *   );
 * }
 * ```
 *
 * @example Dynamic namespace loading
 * ```tsx
 * import { useI18n } from '@comvi/react';
 * import { useState } from 'react';
 *
 * function Dashboard() {
 *   const { t, addActiveNamespace, isLoading } = useI18n();
 *   const [showDashboard, setShowDashboard] = useState(false);
 *
 *   const loadDashboard = async () => {
 *     await addActiveNamespace('dashboard');
 *     setShowDashboard(true);
 *   };
 *
 *   return (
 *     <div>
 *       {!showDashboard ? (
 *         <button onClick={loadDashboard}>
 *           Load Dashboard
 *         </button>
 *       ) : (
 *         <div>{t('title', { ns: 'dashboard' })}</div>
 *       )}
 *     </div>
 *   );
 * }
 * ```
 *
 * @example Adding translations at runtime
 * ```tsx
 * import { useI18n } from '@comvi/react';
 * import { useEffect } from 'react';
 *
 * function MyComponent() {
 *   const { t, addTranslations } = useI18n();
 *
 *   useEffect(() => {
 *     addTranslations({
 *       en: { dynamic: 'Dynamic value' },
 *       fr: { dynamic: 'Valeur dynamique' }
 *     });
 *   }, [addTranslations]);
 *
 *   return <div>{t('dynamic')}</div>;
 * }
 * ```
 *
 * @remarks
 * Re-render behavior: Components using this hook will re-render when any
 * reactive state (locale, translations, isLoading) changes. This is
 * expected and ensures your UI stays in sync with the i18n state.
 *
 * For performance optimization, use React.memo() on components that should
 * skip re-renders when their props haven't changed.
 */
export function useI18n(ns?: string): UseI18nReturn {
  const { i18n, locale, translationCache, isLoading, isInitializing } = useI18nContext();

  // Raw bound translation. Needed by <T> and advanced integrations.
  const tRaw = useMemo(() => createBoundTranslation(i18n, ns) as UseI18nReturn["tRaw"], [i18n, ns]);

  // Text-only translation helper for regular UI copy.
  const t = useMemo(
    () =>
      ((key: string, params?: TranslationParams) =>
        translationResultToString(tRaw(key as never, params as never))) as UseI18nReturn["t"],
    [tRaw],
  );

  // Memoize ALL methods for referential stability in useEffect dependency arrays
  const boundMethods = useMemo(() => {
    const methods = {} as Record<string, unknown>;

    // Bind core methods directly
    for (const m of BIND_METHODS) {
      methods[m] = (i18n[m] as (...a: any[]) => any).bind(i18n);
    }

    // Special wrappers
    methods.setLocale = (loc: string) => i18n.setLocaleAsync(loc);
    methods.onMissingKey = (
      callback: (key: string, locale: string, namespace: string) => string | void,
    ) =>
      i18n.onMissingKey((key, loc, ns) => {
        const result = callback(key, loc, ns);
        return typeof result === "string" || result === undefined ? result : String(result);
      });

    return methods;
  }, [i18n]);

  return {
    t,
    tRaw,
    locale,
    translationCache,
    isLoading,
    isInitializing,
    dir: i18n.dir,
    ...(boundMethods as Omit<
      UseI18nReturn,
      "t" | "tRaw" | "locale" | "translationCache" | "isLoading" | "isInitializing" | "dir"
    >),
  };
}
