// scripts/codemods/framework-slim/__fixtures__/sfc-vue.expected.vue
<!-- Language row — .vue script block, extracted and remapped. -->
<script setup lang="ts">
import { useI18n, useI18nLoader, useI18nPlugins } from "@comvi/vue";

const { t } = useI18n("panel");
const { reloadTranslations } = useI18nLoader();
const { onMissingKey } = useI18nPlugins();
</script>

<template>
  <button @click="reloadTranslations()">{{ t("reload") }}</button>
</template>

// scripts/codemods/framework-slim/__fixtures__/sfc-svelte.expected.svelte
<!-- Language row — .svelte script block, extracted and remapped. -->
<script>
  import { useI18n, useI18nLoader } from "@comvi/svelte";

  const { t } = useI18n("panel");
  const { addActiveNamespace } = useI18nLoader();
</script>

<button on:click={() => addActiveNamespace("late")}>{t("load")}</button>
